### ISSUE TITLE
Auto Bug

### ISSUE THREAD

**Issue by DaRealGitHubDoriitos** [Joshua-Usi/osw#15]
when enabling auto and starting a map, it is still possible to ruin auto by spamming z and x
![image](https://user-images.githubusercontent.com/68355343/144678973-c8290559-08e7-40ae-b722-c18ca9258f9d.png)
(auto was on for this play)

**Comment by Joshua-Usi** [comment]
Yeah thats a problem, i recently disabled moving the mouse with auto but ill make a change to prevent mouse clicks as well

**Comment by Joshua-Usi** [comment]
Disabled user control of keyboard if using auto mods
Resolved in v0.13.0b

**Comment by DaRealGitHubDoriitos** [comment]
Could you put a switch in settings that allows you to actually ruin the gameplay to make it believable? I have friends that have never seen osu! and i want to impress them.

**Comment by Joshua-Usi** [comment]
so you'd like an option for slightly random gameplay to look like a player is playing?

**Comment by DaRealGitHubDoriitos** [comment]
Sorry for the late reply but yes
