### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by DaRealGitHubDoriitos** [Joshua-Usi/osw#16]
Uncaught TypeError: Cannot read properties of undefined (reading 'name')
    at IDBRequest.<anonymous> (main.js:100)

**Comment by DaRealGitHubDoriitos** [comment]
i guess this error is kind of permenant because if i reload the page the error is still there

**Comment by DaRealGitHubDoriitos** [comment]
Restarting cookies is the only option right now

**Comment by Joshua-Usi** [comment]
Can you reproduce the problem and provide steps to reproduce it? Also please use the bug template for these types of issues

**Comment by Joshua-Usi** [comment]
Im not sure the problem is with cookies though, osw does not use or access cookies in any way

**Comment by DaRealGitHubDoriitos** [comment]
1. Open osw!
2. Upload beatmaps
3. Close site during beatmap uploading
4. Restart osw and voila

**Comment by Joshua-Usi** [comment]
Added confirmation before closing window in update v0.13.0b
