### ISSUE TITLE
Console Bug 2

### ISSUE THREAD

**Issue by DaRealGitHubDoriitos** [Joshua-Usi/osw#17]
Access to script at 'file:///media/archive/osw.zip/osw/osw.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.

**Comment by DaRealGitHubDoriitos** [comment]
![image](https://user-images.githubusercontent.com/68355343/144716484-2fffb50b-3e4b-4463-871e-d97a2113646d.png)

**Comment by Joshua-Usi** [comment]
CORS, is a natural part of chrome and unfortunately cannot be disabled. Did you download the project? It cannot be run on local files, you must run it online or using a webserver. A webserver I could reccommend is https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb?hl=en. It will then allow you to run the program

**Comment by DaRealGitHubDoriitos** [comment]
yes i did run it locally which i figured may have been why
