### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by safewallaby** [Joshua-Usi/osw#30]
Do you have a discord server? If not would you like me to make you one so people can request problems, chat, and more?

**Comment by Joshua-Usi** [comment]
Nah its alright. this project is depreciated and abandoned

**Comment by F2-FlassyTTV** [comment]
why is it Abandoned plz keep working on it i think personal it's the best Osu Web Client

**Comment by Joshua-Usi** [comment]
Its not entirely likely that this project will be abandoned forever. However if I do decide to pick it up again. I will most likely do a full rewrite of the app

**Comment by F2-FlassyTTV** [comment]
I Play It Everyday Man Can You Plz Keep Working On It It's The Best Osu!web client i have ever seen and i would love someday for it to have custom skins and mania mode on it
