### ISSUE TITLE
cant put a skin and cant see around circle thing

### ISSUE THREAD

**Issue by jakercat** [Joshua-Usi/osw#31]
**Describe the bug**

**To Reproduce**

**Error/s in console**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Joshua-Usi** [comment]
You need to be more concise and follow the bug report template when submitting a bug report. Without this context. There's not much I can do to fix your issue
