### ISSUE TITLE
sometimes all my maps wont work and i cant play

### ISSUE THREAD

**Issue by DeGamesMG** [Joshua-Usi/osw#32]
**Describe the bug**

**To Reproduce**

**Error/s in console**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Joshua-Usi** [comment]
You need to be more concise and follow the bug report template when submitting a bug report. Without this context. There's not much I can do to fix your issue

However if you scroll to the bottom of the settings menu, you will find several buttons to reset and delete all the currently loaded maps. This may solve your issue
