### ISSUE TITLE
i cant import maps cuz it wont work

### ISSUE THREAD

**Issue by DeGamesMG** [Joshua-Usi/osw#34]
**Describe the bug**

**To Reproduce**

**Error/s in console**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Joshua-Usi** [comment]
You need to be more concise and follow the bug report template when submitting a bug report. Without this context. There's not much I can do to fix your issue
