### ISSUE TITLE
A couple of bugs

### ISSUE THREAD

**Issue by DaRealGitHubDoriitos** [Joshua-Usi/osw#9]
List of bugs found when trying out the game for the first time: 
- When exiting with settings open, the settings gui will stay open until the tab closes it self
- When in mod menu and pressing back, it takes you back to main menu instead of map list, which is kinda frustrating because i play with lazer alot
- Cursor doesnt want to move when starting

**Comment by Joshua-Usi** [comment]
Thank you for providing a bug report, I will work on these problems

**Comment by Joshua-Usi** [comment]
I have resolved 2 out of 3 issues, However I am unaware of any cursor issues, Please open a more formal bug report such as steps to reproduce, system, browser and other info here [here](https://github.com/Joshua-Usi/osw/issues/new?assignees=&labels=bug&template=bug_report.md&title=)
